### ISSUE TITLE
Prepare pycuda wrapper files for each of the cuda kernel files

### ISSUE THREAD

**Issue by mesprague** [zenlc2000/pycuda-euler#3]
Determine if it makes sense to load whole files or add code blocks to python files. Decide if we should import all cuda code at the beginning or one step at a time

**Comment by zenlc2000** [comment]
Initial test of loading the .cu file with multiple kernel methods didn't work, and besides having the kernel code inline isn't too ugly or disruptive. 

My vote is to have one module file for each major section (Encoder, Gpuhash, DebruijnGraph, EulerTour, possibly Component) and import them at the top of the "main" file.

To that end I'm starting with writing the Encoder file and then adapt the code from the cython-based project to call it for ad-hoc testing. Unfortunately without the C version running this code is a little difficult to write tests for. Maybe with a small enough data set an outcome could be hand calculated to test against.
